### ISSUE TITLE
[BUG] - Bad gateway après OAuth

### ISSUE THREAD

**Issue by floutchito** [m4dm4rtig4n/enedisgateway2mqtt#106]
**Description du bug**
Après l'accord de partage de données, la redirection semble très lente, et finit par timeout sur un "Bad Gateway" sur une URL du type `
https://enedisgateway.tech/oauth?code=<code>&state=null&usage_point_id=<pdl>`

**Configuration**
Aucune pour le moment, il s'agit seulement de la creation de l'access_token

**Type d'installation**
Sans objet

**Version : inconnue**

**Comment by m4dm4rtig4n** [comment]
La passerelle avait quelques « balbutiement » depuis quelques temps, je viens de fix 2 3 truc ce soir qui devrait améliorer la stabilité de celle-ci.

**Comment by floutchito** [comment]
Bonjour,

Désolé, mais le problème est toujours présent.

**Comment by m4dm4rtig4n** [comment]
Bon je viens de tester et debug, et en fait je pense que le soucis vient de chez Enedis.
Je viens d'écrire au support.

Normalement, vous devez être redirigé vers ma passerelle avec divers info qui ne sont pas transmise correctent actuellement par Enedis :/
