### ISSUE TITLE
problème fichier yaml.conf

### ISSUE THREAD

**Issue by defaliz** [m4dm4rtig4n/enedisgateway2mqtt#109]
bonjour,
je suis en train d'utiliser docker avec la commande 
docker run -it --restart=unless-stopped -v $(pwd):/data m4dm4rtig4n/enedisgateway2mqtt:latest
j'ai cette erreur
 in "/data/config.yaml", line 41, column 3
expected <block end>, but found '<block mapping start>'
  in "/data/config.yaml", line 42, column 5

j'ai vérifié le fichier aux lignes concernées, les voici : 
une idée ?
je vous remercie

enedis_gateway:
  PDL_1: "mon_pdl"
    token: "mon_token"
    plan: BASE                 # BASE or HP/HC
    consumption: true
    consumption_detail: true
    consumption_price_hc: 0
    consumption_price_hp: 0
    consumption_price_base: 0
    production: false
    production_detail: false

**Comment by alainvdu69** [comment]
bonjour,

il faudrait donner les lignes 41 et 42 du fichier de config vu que c'est là que ça coince

**Comment by fredleger** [comment]
dans ton exmeple il n'y a aucune indentation. Le yaml se sert justement de celle ci pour donner de la structure aux objets tu peux check ici: https://geekflare.com/fr/yaml-introduction/

**Comment by m4dm4rtig4n** [comment]
Hello,

Je suis en train de rework complétement le projet, et la version actuelle deviendra complétement obsoléte.
Je ne traite donc plus de ticket sur cette version.

Merci de patientez encore un petit peu elle ne devrait pas tarder à sortir :)
