### ISSUE TITLE
[BUG] - TypeError: can't multiply sequence by non-int of type 'float'

### ISSUE THREAD

**Issue by slider07210** [m4dm4rtig4n/enedisgateway2mqtt#114]
Bonjour,
Pouvez vous m'aider, j'ai l'erreur suivante : TypeError: can't multiply sequence by non-int of type 'float'
MQTT m'a bien créé mon appareil Linky avec seulement 3 capteurs : last_activation_date, last_distribution_tariff_change_date, subscribed_power.

ci-dessous ma configuration.

Merci beaucoup 

Aurélien

Configuration:
cycle: 3600
debug: true
enedis_gateway:
  xxxxxxxxxxxxxx:
    token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx9zz556o
    addresses: true
    consumption: true
    consumption_detail: true
    consumption_price_base: "0,1821"
    consumption_price_hc: "0,1360"
    consumption_price_hp: "0,1821"
    plan: BASE
    production: false
    production_detail: false
    refresh_addresses: false
    refresh_contract: false
home_assistant:
  card_myenedis: true
  discovery: true
  discovery_prefix: homeassistant
mqtt:
  client_id: enedis_gateway
  host: 192.168.x.xx
  password: 'xxxxxxxx'
  port: 1883
  prefix: enedis_gateway
  qos: 0
  retain: true
  username: 'xxxxxxx'
wipe_cache: false

Type d'installation :
HassIO

Version : 0.7.7-3

**Comment by phenixtai** [comment]
idem pour moi, même aprés réinstallation complete de l'addon + mosquitto.
-->
Traceback (most recent call last):
  File "/app/main.py", line 656, in <module>
    run(pdl, pdl_config)
  File "/app/main.py", line 292, in run
    ha_discovery_consumption = day.getDaily(headers, cur, con, client, pdl, pdl_config, "consumption",
  File "/app/daily.py", line 82, in getDaily
    roundValue = round(int(current_value) / 1000 * base_price, 2)
TypeError: can't multiply sequence by non-int of type 'float'
[15:46:30] FATAL: The app has crashed. Are you sure you entered the correct config options?

**Comment by phenixtai** [comment]
Ha ok, mettre des points a la place des virgule à corriger mon erreur ...
-->
debug: false
enedis_gateway:
  19XXXXXXXXXXX:
    addresses: false
    consumption: true
    consumption_detail: true
    consumption_price_base: 0.21
    consumption_price_hc: 0.01
    consumption_price_hp: 0.21
    plan: BASE
    production: false
    production_detail: false
    refresh_addresses: false
    refresh_contract: false
    token: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXoaxYQ
home_assistant:
  card_myenedis: true
  discovery: true
  discovery_prefix: homeassistant
mqtt:
  client_id: enedis_gateway
  host: XXXXXXXXXXX.10
  password: ''
  port: 1883
  prefix: enedis_gateway
  qos: 0
  retain: true
  username: ''
wipe_cache: false

**Comment by phenixtai** [comment]
consumption_price_base: 0.21
consumption_price_hc: 0.01
consumption_price_hp: 0.21

et non : 

consumption_price_base: "0,1821"
consumption_price_hc: "0,1360"
consumption_price_hp: "0,1821"

est ce que cela t'aide *?

**Comment by phenixtai** [comment]
Par contre j'ai toujours : 
API Call number per day is reached (15), please wait until tomorrow to load the rest of data

bien que j'ai cycle: 3600

**Comment by slider07210** [comment]
> Par contre j'ai toujours : API Call number per day is reached (15), please wait until tomorrow to load the rest of data
> 
> bien que j'ai cycle: 3600

Bonjour phenixtai,
merci beaucoup pour ton éclairage, effectivement maintenant ça fonctionne toutes mes données sont bien remontées dans MQTT et HA.
En espérant que cela soit fiable et durable dans le temps.
Bonne soirée

**Comment by phenixtai** [comment]
top, content d'avoir pu aider :)

**Comment by m4dm4rtig4n** [comment]
Hello,

Je suis en train de rework complétement le projet, et la version actuelle deviendra complétement obsoléte.
Je ne traite donc plus de ticket sur cette version.

Merci de patientez encore un petit peu elle ne devrait pas tarder à sortir :)
