### ISSUE TITLE
[BUG] - Récupération token

### ISSUE THREAD

**Issue by ElectroFactory** [m4dm4rtig4n/enedisgateway2mqtt#116]
Lors de la validation de la demande de consentement je reçoit un mail incluant mon numéro de pdl mais sur le site rien ne se passe et le token ne s'affiche pas.

**Comment by pbranly** [comment]
Bonjour
C'est un bug d'énedis
Ils sont au courant 
Il faut attendre ....

**Comment by m4dm4rtig4n** [comment]
Hello,

Je suis en train de rework complétement le projet, et la version actuelle deviendra complétement obsoléte.
Je ne traite donc plus de ticket sur cette version.

Merci de patientez encore un petit peu elle ne devrait pas tarder à sortir :)
