### ISSUE TITLE
[BUG] - Crash dans certains cas de mauvaise réponse des API

### ISSUE THREAD

**Issue by cyberden** [m4dm4rtig4n/enedisgateway2mqtt#119]
**Description du bug**
J'ai un plantage régulier, probablement en raison d'un echec de l'appel à l'api (401) qui renvoi des mauvaises données et donc ça crash.

Quand je relance le container, en général ça refonctionne tout de suite.

**Configuration**
enedis_gateway:
  "XXXXXXXXXXXXXX ":              # Replace XXXXXXXXXXXXXX by your PDL Number. MANDATORY
    token: "MON TOKEN"          # MANDATORY
    plan: BASE                 # BASE or HP/HC
    consumption: true                 
    consumption_detail: true         
    consumption_price_hc: 0           
    consumption_price_hp: 0           
    consumption_price_base: 0         
    production: false                 
    production_detail: false          
    offpeak_hours: ""         # USE ONLY IF YOU WANT OVERLOAD DEFAULT VALUE, Format : 22h36-06h00;11h30-14h30
    addresses: true

**Type d'installation**
Docker

**Version : X.X.X**
Docker latest image (0.7.7)

Le log de l'erreur est :
`
2022-08-04 17:10:05.714956 - INFO  : ==> error => token_refresh_401

2022-08-04 17:10:05.715117 - INFO  : ==> description => Une erreur est survenue, merci de renouveller vos consentements.

2022-08-04 17:10:05.715297 - INFO  : ==> user_alert => True

TypeError: string indices must be integers
    current_value = int(value["value"])
  File \"/app/daily.py\", line 48, in getDaily
    ha_discovery_consumption = day.getDaily(headers, cur, con, client, pdl, pdl_config, \"consumption\",
  File \"/app/main.py\", line 292, in run
    run(pdl, pdl_config)
  File \"/app/main.py\", line 656, in <module>
Traceback (most recent call last):
`

**Comment by m4dm4rtig4n** [comment]
Hello,

Je suis en train de rework complétement le projet, et la version actuelle deviendra complétement obsoléte.
Je ne traite donc plus de ticket sur cette version.

Merci de patientez encore un petit peu elle ne devrait pas tarder à sortir :)
