### ISSUE TITLE
[HELP] - can the sensor used as a source for the energy dashboard

### ISSUE THREAD

**Issue by fredleger** [m4dm4rtig4n/enedisgateway2mqtt#120]
MERCI DE RESPECTER LES DIFFERENTS CHAMPS SINON JE CLOS L'ISSUE.

**Description de la fonctionnalité**
Je suis un peu confus par la doc. Peut t'on utiliser cet addon comme source de consomation d'énérgie dnas le dashboard energy de HA. Si oui quel est le sensor exact ? J'ai pour l'instant utilisé `sensor.enedisgateway_xxxxxxxxxx_consumption_this_month` mais il ne semble pas incrémenté

**Type d'installation**
HassIO

**Version : X.X.X**
0.7.7-3

**Comment by milouze03400** [comment]
salut as tu trouvé une solution pour utiliser comme source de consommation d’énergie dans le dashboard energy ?

**Comment by fredleger** [comment]
Non pas du tout, j'ai basculé sur une clé Lixee pour avoir la fonctionnalité

Le jeu. 29 sept. 2022 à 10:49, milouze03400 ***@***.***> a
écrit :

**Comment by m4dm4rtig4n** [comment]
Hello,

Je suis en train de rework complétement le projet, et la version actuelle deviendra complétement obsoléte.
Je ne traite donc plus de ticket sur cette version.

Merci de patientez encore un petit peu elle ne devrait pas tarder à sortir :)
