### ISSUE TITLE
units definitions

### ISSUE THREAD

**Issue by pbranly** [m4dm4rtig4n/enedisgateway2mqtt#26]
1: In the field enedisgateway_daily: except a difference of a factor of1000, fields W et kW sont identical; 
In addition, unity for both case are kWh instead of W and kW.
2: In the field enedisgateway_detail: 
The field Wh is not good as datas are given every 1/2h. W or kW should be used for 1/2 h increment

**Comment by m4dm4rtig4n** [comment]
1. fix in 0.5.4

**Comment by pbranly** [comment]
Fix does not include :
- in the daily field: Wh and kWh are the same except a factor of 1000
- In the detail field, there are still energy fields ( in xxH) while values are by step of 1/2 h

**Comment by m4dm4rtig4n** [comment]
* in the daily field: Wh and kWh are the same except a factor of 1000

Je vois pas où est le problème en fait :D 

* In the detail field, there are still energy fields ( in xxH) while values are by step of 1/2 h

Bah perso je récupère des données en W par tranche de 10 ou 30 ou 60min, du coup j'insert tt ce que je récupère avec la méthode suivante : 
```
        value = result[2]
        value_kw = value / 1000
        value_wh = value * interval_length / 60
        value_kwh = value_wh / 1000
        current_price = forceRound(value_kwh * price[measure_type], 4)
        f.log(f"Insert detail {date} => {value}", "DEBUG")
        dateObject = datetime.strptime(date, '%Y-%m-%d %H:%M:%S') - relativedelta(hours=2)
        p = influxdb_client.Point("enedisgateway_detail") \
            .tag("pdl", pdl) \
            .tag("measure_type", measure_type) \
            .tag("interval", interval_length) \
            .tag("year", dateObject.strftime("%Y")) \
            .tag("month", dateObject.strftime("%m")) \
            .field("W", int(value)) \
            .field("kW", forceRound(int(value_kw), 2)) \
            .field("Wh", forceRound(int(value_wh), 2)) \
            .field("kWh", forceRound(int(value_kwh), 2)) \
            .field("price", current_price) \
            .time(dateObject) 
```
Je vois pas forcement où est le problème ;D

**Comment by pbranly** [comment]
Pour le daily, ce n’est pas une erreur. C’est juste qu’à mon sens, il est inutile de remplir une base de données de 2 chiffres qui sont exactement les meme à un coef de 1000 près. Un seul serait suffisant , charge aux applications de faire le traitement sur le coef en fonction du résultat voulu. Ce point est de nature mineure 

Pour le détail, c’est pareil: tu gères des W et des KW. Un seul est suffisant .
Puis tu fabriques des pseudos Wh doublés par des kWH en considérant que la valeur sur une heure est celle de la puissance données chaque « delta T »/delta T* 60.
Ce sont vraiment des pseudos (k)Wh car si la valeur n’existe que pendant 1/2 h et rien la demie heure suivante, ton pseudo (k)Wh sera  à divider par 2. Pour moi ces valeurs ne sont pas utilisables telles qu’elles sauf à ré analyser le contenu de chaque 1/2 heure suivante ( ou delta T si ce n’est pas toutes les 1/2 h)
Pour moi une seule valeur brute en W doit être stockée dans la base. Des calculs ultérieurs sont à la charge d’applications différents. Pour moi c’est plus majeur pour ce qui concerne ces pseudo (k)Wh

Philippe

**Comment by m4dm4rtig4n** [comment]
Bah c'est parce que j'ai l'info et que ca facilite le taff après sur grafana & co.
Après c'est juste que ko de data c'est pas ca qui va surcharger la bdd :p
