### ISSUE TITLE
Problème installation

### ISSUE THREAD

**Issue by mellowtronik** [m4dm4rtig4n/enedisgateway2mqtt#39]
Bonjour,

Je débute sur HA mais habituellement j'arrive a installer des intégrations mais je n'arrive pas à installer la votre...
J'ai téléchargé le fichier zip, dézippé puis je l'ai mis dans custom_components, redémarrer HA et j'ai recherché dans HACS mais il ne me trouve pas enedisgateway2mqtt...?
Est-ce que cette intégration s'installe autrement? J'ai également essayé avec l'adresse github (https://github.com/m4dm4rtig4n/enedisgateway2mqtt) directement via Hacs mais j'ai une erreur qui dit: (Repostitory structure for master is not compliant)
J'ai vraiment envie de tester votre intégration, donc je vous remercie par avance pour votre aide.
Cordialement,

**Comment by mellowtronik** [comment]
Bonjour,

Merci pour ta réponse rapide. Ok je comprends mieux.
Alors oui, j'utilise HA HassoS. Le lien que tu m'as donné est invalide (erreur 404)
Concernant le Docker, vraiment désolé mais je n'y connais rien du tout.
Te serait-il possible de me donner un lien valide pour l'addon alexbelgieum, stp?
Encore merci?

**Comment by mellowtronik** [comment]
Pas de soucis, la page s'ouvre mais ça me dis (Les téléchargements sont désactivés.
Les téléchargements de fichiers nécessitent un accès push à ce référentiel.) décidément, je n'ai pas de bol..

**Comment by mellowtronik** [comment]
Bonsoir, je suis Pascal Djaron de Facebook, serait possible d'avoir plus d'infos pour le paramétrage de ton api, stp ? J'ai installé la version de alexbelgium. Et l'api se trouve sous Supervisor. J'ai rentré mon pdl et mon token mais je ne sais pas comment faire après pour faire apparaître les infos conso dans mon lovelace (dashboard)
Merci par avance de ton aide.

**Comment by m4dm4rtig4n** [comment]
Tu as bien MQTT ?

**Comment by mellowtronik** [comment]
Oui j'ai bien Mqqt. Mais j'ai beau chercher comment mettre enedisgateway2mqtt dans le lovelace pour avoir les infos sur mon compteur mais je ne sais pas comment il faut faire..

**Comment by m4dm4rtig4n** [comment]
Pour lovelace tu peut utilise la carte de Saniho [ICI](https://github.com/saniho/content-card-linky).

Normalement si tout est bon, et que tu as bien activé le discovery MQTT tu doit avoir un sensor du type :
sensor.enedisgateway_TONPDL

Il te reste à renseigner le sensor en question dans la carte de Saniho.

**Comment by mellowtronik** [comment]
Normalement je pense avoir tout bien fait sur Mqtt et je n'ai pas l'entité que tu me dis j'ai seulement ce que tu peux voir dans mon screenshot 🤔
![Screenshot_2021-11-12-12-57-27-649_io homeassistant companion android](https://user-images.githubusercontent.com/91826922/141463789-ce65c5a6-43a9-45a3-afe2-97fc305f66ec.jpg)

**Comment by mellowtronik** [comment]
Bonjour,
Bon, j'ai tout supprimé, tout réinstallé, etc.. et ça ne fonctionne pas l'entité sensor.enedisgateway_TONPDL

Je ne sais plus quoi faire. Cependant qu'appelles-tu par (activé le discovery MQTT ) ?

J'ai installé MQTT brocker, MQTT dans intégrations, crée un nouvel utilisateur MQTT, paramétré endisgateway2mqqt sur SUPERVISOR comme ton tuto mais je n'ai pas toutes les lignes, (surement car je suis sur HASS.OS)

Quand je vais dans Supervisor/endisgateway2mqqt puis journal, je n'ai aucun message d'erreur...Donc je ne comprends pas.

Il ne te serait pas possible de faire une version via intégrations, pour Home Assistant HASS.OS? ça serait plus simple (je pense)

Voilà, j'attends ton retours si possible, j'aurai tellement voulu tester ton projet...

Merci d'avance et bonne journée.

**Comment by m4dm4rtig4n** [comment]
Sur home assistant, il existe une fonctionnalité MQTT qui s'appelle le [MQTT discovery](https://www.home-assistant.io/docs/mqtt/discovery/).

Si tu n'a pas activer cette fonctionnalité sur HA, les sensors que je crée via enedisgateway2mqtt ne seront jamais remonté dans HA.
Après tu peut faire sans bien sûr, mais c'est à toi de crée le sensor manuellement et le faire pointer sur la bonne queue.
Je te conseille d'utiliser un outils MQTT Explorer qui va te permettre de visualiser les info stocker dans MQTT.
