### ISSUE TITLE
Décalage de date dans la remontée

### ISSUE THREAD

**Issue by navycrow** [m4dm4rtig4n/enedisgateway2mqtt#48]
Bonjour.
Il me semble qu'il y a une erreur d'affectation de la journée dans la remonté des consos.

Par exemple, sur le site Enedis, j'ai :
![image](https://user-images.githubusercontent.com/4997731/141789830-c90cbb0c-659b-44bb-a2f4-956608b69c75.png)

Alors que l'addon affiche ceci :
![image](https://user-images.githubusercontent.com/4997731/141789938-4d09c943-aaef-4119-a7b9-54318caed665.png)

De plus je constate dans les attributs une valeur erronée pour la date d'hier :
Nous sommes aujourd'hui le 15/11 donc hier le 14/11 et l'attribut YesterdayDate indique le 13/11
![image](https://user-images.githubusercontent.com/4997731/141798299-139d87da-ca93-4446-8bb5-117a5c93d18c.png)

Merci beaucoup pour le boulot réalisé jusqu'à présent !!!

**Comment by pbranly** [comment]
Le décalage de date est du à un décalage sur le docker 
Rajoutez 

      - TZ=Europe/Paris
Dans les variables d'environnement, relancez et ce sera bon 
Philippe

**Comment by navycrow** [comment]
d'abord merci pour la réponse.
Je viens de passer à Home Assistant, il y a un mois. J'ai appris énormément de chose et fait beaucoup de progrès mais il y a encore des choses que je ne maitrise (mais je m'y attèle avec un peu d'indulgence... ;) )
Là, je coince. Ou et comment je fais cela ???

**Comment by pbranly** [comment]
Vous utilisez la version addon ?
Si oui je ne sais pas 
Désolé 
Madmartigan répondra 
Phil

**Comment by navycrow** [comment]
Oui effectivement.
Pas grave ! On va attendre....
Ps : merci pour le PDL (erreur de débutant), c'est corrigé ;)

**Comment by m4dm4rtig4n** [comment]
Je confirme ce que @pbranly à dit, les fois où j'ai remarquer ce genre de soucis c'était lié à un mauvais timezone et génére un décalage de jours.
Après sur Hassio aucune idée de comment set le TZ :/

**Comment by alexbelgium** [comment]
> Vous utilisez la version addon ? Si oui je ne sais pas Désolé Madmartigan répondra Phil Ps/ ne mettez pas votre pdl en clair

Ok je rajoute ça dans la version suivante de l'addon !

**Comment by pbranly** [comment]
Ce qui a été constaté c’est que sans la variable TZ= Europe/Paris, le docker se met en heure UTC donc une heure de moins en ce moment qu’avec la variable qui force le docker CET.
Donc sans la variable, le point jour J a 0h30 devient J-1 a 23h30

**Comment by m4dm4rtig4n** [comment]
C'est effectivement une solution :D

**Comment by m4dm4rtig4n** [comment]
@navycrow j'ai intégrée la fonctionnalité dans la 0.7.1.
Dit moi si ca corrige ton soucis.

**Comment by navycrow** [comment]
Bonjour,
Je viens d'installer la 0.7.1 et apparemment ça à l'air effectivement d'avoir résolu ce problème.
Merci beaucoup !!! :)

**Comment by pbranly** [comment]
Oui cela fonctionne avec l'intégration les sensors qui arrivent via mqtt dans HA
Par contre, cela reste décalé dans influxdb. Je verrai demain si ça va mieux car pour l'instant je suis brûlé !
Philippe

**Comment by YNK-22** [comment]
Perso même avec la TZ Europe/Paris je garde le décalage de -1h, je suis en 0.7.3 sur l'addon Hassos, si vous avez une idée?

**Comment by YNK-22** [comment]
Pour mon soucis de jour décalé, peut-on faire un wipe data dans la nouvelle maj 0.7.4 une fois que l'erreur au démarrage sera résolu ?

**Comment by alexbelgium** [comment]
Techniquement il suffit :
- de démarrer l'addon au moins une fois pour créer les liens
- puis aller /config/enerdisgateway2mqtt et supprimer le fichier enedisgateway.db (ou le renommer si tu veux le garder au cas où)
- redémarrer l'addon et la nouvelle base sera créée

**Comment by m4dm4rtig4n** [comment]
Sinon il est possible de mettre dans le config.yaml
```
wipe_cache: true
```
Par contre attention, il faut le remettre à false direct (ou retirer la ligne) sinon le cache sera wipe à chaque restart de l'addon :/

**Comment by YNK-22** [comment]
oui oui c'est juste pour m'afficher les bonnes valeurs au niveau des jours (un décalage d'une journée), j'attends le fix de la version 0.7.5 pour le faire 👍

**Comment by alexbelgium** [comment]
version 0.7.5 en place :-)

**Comment by alexbelgium** [comment]
Version 0.7.5-2 en place. En fait je me rend compte que la variable TZ ne change rien en environnement. J'ai rajouté le code "ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone" et un descriptif dans le log qui ne s'affiche que si on change le TZ

Je l'ai mis en script bash mais voici ce qu'il faudrait en dockerfile : 
ENV TZ=America/Los_Angeles
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
https://stackoverflow.com/questions/40234847/docker-timezone-in-ubuntu-16-04-image

**Comment by YNK-22** [comment]
pour moi un wipe data = true (pour le premier démarrage) a suffit à remettre les bonnes data 👍

**Comment by m4dm4rtig4n** [comment]
Dans l'insertion dans l'influxdb je viens de m'appercevois que j'ai merder dans l'insert style avec un -2h sur tt ce que j'insert.
Je viens de le retirer à tester maintenant.

**Comment by pbranly** [comment]
je viens de tester ; ca fonctionne mais ca ajoute les nouvelles valeurs dans influxdb sans supprimer les anciennes

**Comment by m4dm4rtig4n** [comment]
Bon une 0.7.7-dev va sortir avec "normalement" plus de soucis au niveau des TZ.
J'ai forcer le TZ des données que j'insert.
