### ISSUE TITLE
Proposition : config.yaml template

### ISSUE THREAD

**Issue by alexbelgium** [m4dm4rtig4n/enedisgateway2mqtt#49]
@M4dm4rtig4n: Que pense tu de mettre un fichier config.yaml template avec une commande dans ton script start de type [ ! -f /data/config.yaml ] && cp /template/config.yaml /data/? Ainsi le user qui installe pour la première fois n'aura qu'à customizer plutôt que de repartir de la syntaxe du repo.

**Comment by m4dm4rtig4n** [comment]
Yep je me met sa dans la todo :)

**Comment by m4dm4rtig4n** [comment]
Fait.
