### ISSUE TITLE
Problème HC/HP

### ISSUE THREAD

**Issue by alexbelgium** [m4dm4rtig4n/enedisgateway2mqtt#52]
Issue from @YNK-22 :

Tout d'abord merci pour cet Addon, très bien fait et bien pensé !

Mais j'ai encore quelques soucis, notamment au niveau des heures creuses/heures pleines lorsque j'indique mes heures creuses voici ce que j'obtiens dans les logs, à noter que j'ai indiqué mes HC de cette façon OFFPEAK_HOURS: 00h00-06h24;22h24-23h59

"Linky", "manufacturer": "Enedis"}} Traceback (most recent call last): File "/app/main.py", line 640, in <module> run() File "/app/main.py", line 565, in run my_enedis_data = myenedis.myEnedis(cur, con, client, last_activation_date, offpeak_hours) File "/app/myenedis.py", line 414, in myEnedis dateBegin = today.replace(hour=int(plage[0].split("H")[0]), minute=int(plage[0].split("H")[1]), second=0) ValueError: invalid literal for int() with base 10: '00h00' [10:36:24] FATAL: The app has crashed. Are you sure you entered the correct config options? exit 0

Et deuxième question : J'ai souvent le message d'erreur comme quoi j'ai atteint la limite des 50 appels de l'API mais a t'on moyen de mettre une limite ?

Merci beaucoup !

**Comment by m4dm4rtig4n** [comment]
Merci ;)

Alors pour ce qui est des HP/HC, si tu est effectivement sur un contrat HC/HP pas besoin de définir les OFFPEAK_HOURS, je vais récupérer les valeurs directement chez Enedis.

OFFPEAK_HOURS, permet juste de surcharger les valeurs remonter par Enedis.
Et dans ton cas, il suffit de déclarer : OFFPEAK_HOURS: 22h24-06h24 car je gérée déjà les sauts de jours.

Pour la limte des 50 appels tu ne devrait plus l'avoir d'ici quelques jours, c'est probablement parce que tu est dans une phase de chargement du cache qui récupére 3 ans d'historique en daily et 2 en détail et génére donc bcp d'appel : https://github.com/m4dm4rtig4n/enedisgateway2mqtt#enedis-gateway-limit

**Comment by YNK-22** [comment]
Super merci pour les réponses rapides !
J'ai effectué la dernière maj et j'ai un soucis je ne sais pas si je dois ouvrir une autre issue mais voilà ce que j'obtiens au niveau des logs :

`scripts/99-run.sh: executing
Using config file found in /config/enedisgateway2mqtt/config.yaml
./scripts/99-run.sh: line 23: EXIT_CODE: unbound variable
scripts/99-run.sh: exiting 1`

**Comment by alexbelgium** [comment]
Merci, je check

**Comment by alexbelgium** [comment]
voilà, corrgé je pousse une nouvelle version

**Comment by YNK-22** [comment]
Ok merci beaucoup pour ta réactivité, je vais attendre la maj sur l'addon Hassos 👌🏼

**Comment by YNK-22** [comment]
hello, de nouveau moi, j'obtiens cette erreur après la maj : 


`Traceback (most recent call last):
  File "/app/main.py", line 619, in <module>
    run(pdl, pdl_config)
  File "/app/main.py", line 208, in run
    addresse = addr.getAddresses(headers, client, con, cur, pdl, pdl_config)
  File "/app/addresses.py", line 37, in getAddresses
    addresses = queryApi(url, headers, data)
  File "/app/addresses.py", line 14, in queryApi
    addresses = f.apiRequest(cur, con, pdl, type="POST", url=f"{url}", headers=headers, data=json.dumps(data))
  File "/app/function.py", line 132, in apiRequest
    retour = requests.request(type, url=f"{url}", timeout=240, headers=headers, data=data).json()
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.9/http/client.py", line 1279, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.9/http/client.py", line 1320, in _send_request
    self.putheader(hdr, value)
  File "/usr/local/lib/python3.9/http/client.py", line 1257, in putheader
    raise ValueError('Invalid header value %r' % (values[i],))
ValueError: Invalid header value b'0.7.3\n'
[20:20:52] FATAL: The app has crashed. Are you sure you entered the correct config options?`

**Comment by m4dm4rtig4n** [comment]
Erreur de ma part je viens de relancer un rebuild de la 0.7.3.
Un "\n" c'était glissé au mauvais endroit :/

**Comment by m4dm4rtig4n** [comment]
Erreur de ma part je viens de relancer un rebuild de la 0.7.3.
Un "\n" c'était glissé au mauvais endroit :/

**Comment by YNK-22** [comment]
Merci beaucoup, l'addon se lance bien désormais 👌🏼 je dois peaufiner la TZ mais j'ai vu ça dans une autre issue 👍🏼
