### ISSUE TITLE
Différence entre la somme HP+HC et BASE + calcul du tarif

### ISSUE THREAD

**Issue by navycrow** [m4dm4rtig4n/enedisgateway2mqtt#54]
Bonsoir,
Je suis sur la v0.7.3 et je remarque 3 bizarreries : 
1. Si je fais la somme HP+HC, j'ai quasi systématiquement une différence avec le total CONSO de presque 0.2 kwh.
2. Le calcul du tarif des HP/HC ne semble pas tenir compte des tarifs HP / HC que j'ai renseigné dans le config.yaml et utilise le tarif BASE.
3. Il y a une inversion entre les HP/HC qui apparaissent en haut et celles qui apparaissent en bas à droite dans le tableau

![image](https://user-images.githubusercontent.com/4997731/142272547-e20ee069-e113-473e-b187-75fe5a70276e.png)
![image](https://user-images.githubusercontent.com/4997731/142271246-6867ebc2-fda7-41d3-a1e2-63adf2bd6fe6.png)

**Comment by m4dm4rtig4n** [comment]
1. Il y a un soucis de TimeZone, qui peut faire que tu décale d'1h ta conso d'un jour à l'autre et peut généré cette légère diff sur le mode "detail"
2. Effectivement, je vais regarder ca.
3. Pour le price HC/HP sur la card, j'ai déjà remarquer et je pense que c'est un soucis dans la card car dans mon card je transfert bien l'info au bonne endroit normalement :/
Regarde le sensor.enedisgateway_TONPDL, dailyweek_costHP contient vient les valeurs HP et dailyweek_HC les valeurs HC normalement

**Comment by navycrow** [comment]
oui : dailyweek_HP contient bien les valeurs HP et dailyweek_HC les valeurs HC
![image](https://user-images.githubusercontent.com/4997731/142486468-4f5915a4-f878-455c-a373-85cbc1ce3c54.png)

**Comment by m4dm4rtig4n** [comment]
Pour le soucis sur la card, je viens de remonter le soucis à Saniho (dev de la card) et il va faire le fix.

**Comment by m4dm4rtig4n** [comment]
On me dit dans l'oreille que le fix sur l'inversion HC/HP de la card est en production !

**Comment by navycrow** [comment]
Ah. C'est une bonne nouvelle !! Merci :)

**Comment by m4dm4rtig4n** [comment]
Pour la 1. c'est un soucis de TZ qui actuellement en train d'etre traiter dans un autre ticket.
Pour la 2. et 3. tt est fix dans la 0.7.7.

Je clos l'issue
