### ISSUE TITLE
Impossible de noter le PDL

### ISSUE THREAD

**Issue by schumissimo63** [m4dm4rtig4n/enedisgateway2mqtt#56]
Bonjour à tous,

Je suis en 0.7.3 et il m'est impossible de rentrer le PDL, je n'ai aucun endroit où le renseigner et j'ai ce message d'erreur: 

`[08:13:21] INFO: Starting the app
 
2021-11-18 07:13:25.680754 - ERROR : Some mandatory parameters are missing :
2021-11-18 07:13:25.680913 - ERROR : - PDL must be 14 characters (pdl => 3)
2021-11-18 07:13:25.681089 - ERROR : 
2021-11-18 07:13:25.681233 - ERROR : You can get list of parameters here :
2021-11-18 07:13:25.681432 - ERROR :  => https://github.com/m4dm4rtig4n/enedisgateway2mqtt#configuration-file
2021-11-18 07:13:25.681583 - CRITICAL : -- Stop application --
`

Mon config.yaml

`cycle: 3600
debug: false
enedis_gateway:
  pdl:
    addresses: true
    consumption: true
    consumption_detail: true
    consumption_price_base: 0
    consumption_price_hc: 0
    consumption_price_hp: 0
    offpeak_hours: null
    plan: BASE
    production: false
    production_detail: false
    refresh_addresses: false
    refresh_contract: false
    token: XXX
home_assistant:
  card_myenedis: true
  discovery: true
  discovery_prefix: homeassistant
mqtt:
  client_id: enedis_gateway
  host: XXX
  password: 'XXX'
  port: 1883
  prefix: enedis_gateway
  qos: 0
  retain: true
  username: 'XXX'
wipe_cache: false

`

**Comment by darthmamour** [comment]
Bonjour, la meme, soit je change l'indentation et cela ne marche pas, soit je mets le pal mais cela crash l'app.

**Comment by darthmamour** [comment]
`enedis_gateway:  
  PDL_1: XXXXXXXXXXX # MANDATORY
    token: XXXXXXXXXXXXX
    plan: BASE                 # BASE or HP/HC
    consumption: true                 
    consumption_detail: true         
    consumption_price_hc: 0           
    consumption_price_hp: 0           
    consumption_price_base: 0         
    production: false                 
    production_detail: false          
#    offpeak_hours: ""        # USE ONLY IF YOU WANT OVERLOAD DEFAULT VALUE, Format : 22h36-00h10;01h00-06h00
    addresses: true`

**Comment by schumissimo63** [comment]
Le renseignements des données doit se faire dans le config.yaml directement et plus dans l'onglet "configuration" comme on le faisait précédemment, du moins c'est ce que je pense.

**Comment by darthmamour** [comment]
c'est ce que j'ai fait...

**Comment by m4dm4rtig4n** [comment]
Problème d'indentation YAML :
```
enedis_gateway:  
  TON_NUMERO_DE_PDL:
    token: TON_TOKEN
    plan: BASE
    consumption: true                 
    consumption_detail: true         
    ...
```

**Comment by darthmamour** [comment]
Merci!!

**Comment by schumissimo63** [comment]
Merci bien, ça marche nickel maintenant ;)
