### ISSUE TITLE
Problème avec la 7.4 error trailing spaces

### ISSUE THREAD

**Issue by darthmamour** [m4dm4rtig4n/enedisgateway2mqtt#62]
Starting scripts :
scripts/00-aaa_dockerfile_backup.sh: executing
scripts/00-banner.sh: executing
-----------------------------------------------------------
 Add-on: Enedisgateway2mqtt
 use Enedis Gateway API to send data in your MQTT Broker
-----------------------------------------------------------
 Add-on version: 0.7.4
 You are running the latest version of this add-on.
 System: Home Assistant OS 6.6  (aarch64 / raspberrypi3-64)
 Home Assistant Core: 2021.11.4
 Home Assistant Supervisor: 2021.10.8
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
 https://github.com/alexbelgium/hassio-addons
-----------------------------------------------------------
scripts/99-run.sh: executing
[13:27:02] INFO: Using config file found in /config/enedisgateway2mqtt/config.yaml
/config/enedisgateway2mqtt/config.yaml
  40:16     error    trailing spaces  (trailing-spaces)
  44:22     error    trailing spaces  (trailing-spaces)
  45:29     error    trailing spaces  (trailing-spaces)
  46:33     error    trailing spaces  (trailing-spaces)
  47:33     error    trailing spaces  (trailing-spaces)
  48:30     error    trailing spaces  (trailing-spaces)
  49:22     error    trailing spaces  (trailing-spaces)
  50:29     error    trailing spaces  (trailing-spaces)
[13:27:04] FATAL: Config file has an invalid yaml format. Please check the file in /config/enedisgateway2mqtt/config.yaml. Errors list above. You can check yaml validity with the online tool yamllint.com
scripts/99-run.sh: exiting 1

**Comment by YNK-22** [comment]
Salut, j'ai déjà eu le soucis, dans ta conf sur le fichier "conf.yaml" il y a des espaces en trop à la fin de certaines lignes

**Comment by darthmamour** [comment]
d'accord je regarde

**Comment by darthmamour** [comment]
ok probleme initial résolu...
Nouveau en cours...

2021-11-18 12:48:41.308845 - INFO  : Get contract :
2021-11-18 12:48:41.311263 - INFO  :  => Query API
Traceback (most recent call last):
  File "/app/main.py", line 622, in <module>
    run(pdl, pdl_config)
  File "/app/main.py", line 185, in run
    contract = cont.getContract(headers, client, cur, con, pdl, pdl_config)
  File "/app/contract.py", line 38, in getContract
    contract = queryApi(url, headers, data)
  File "/app/contract.py", line 15, in queryApi
    contract = f.apiRequest(cur, con, pdl, type="POST", url=f"{url}", headers=headers, data=json.dumps(data))
  File "/app/function.py", line 108, in apiRequest
    query_result = json.loads(query_result[0][1])
IndexError: list index out of range
[12:48:41] FATAL: The app has crashed. Are you sure you entered the correct config options?

**Comment by m4dm4rtig4n** [comment]
Le fix arrive avec la 0.7.5.
Désolé, mais je pousse bcp de fix en ce moment j'ai quelques rater :p

**Comment by schumissimo63** [comment]
J'ai la meme erreur, ce n'est pas grave pour le nombre de fix, merci pour ton taff ;)

**Comment by YNK-22** [comment]
oui merci tu es très réactif !

**Comment by m4dm4rtig4n** [comment]
Et avec la 0.7.6 ?

**Comment by YNK-22** [comment]
Perso je n'ai plus l'erreur cité ci dessus mais il ne donne pas les heures creuses et les heures pleines, seulement le global (j'ai bien mis HP/HC)

**Comment by m4dm4rtig4n** [comment]
Ta bien activer le relevé horaire ?

**Comment by YNK-22** [comment]
Sur le site enedis ? Oui

**Comment by m4dm4rtig4n** [comment]
Ticket en double :
https://github.com/m4dm4rtig4n/enedisgateway2mqtt/issues/67
