### ISSUE TITLE
[BUG] - décalage d’une journée pour les datas daily mémorisées dans InfluxDB

### ISSUE THREAD

**Issue by pbranly** [m4dm4rtig4n/enedisgateway2mqtt#65]
**Describe the bug**

 En gros : la règle immuable est que InfluxDB écrit toujours en UTC.
Enedis donne ses valeurs du jour à 0:30 en heure locale donc en CET. INFLUXDB écrit donc la valeur d’énergie a 23h30 du jour précédent pour nous qui sommes en CET.
Tout le problème est donc le choix d’Enedis de donner en tout début de journée le cumul d’énergie de toute la journée. La logique voudrait que cette valeur soit donnée chaque jour à 23h59 .
Solutions possibles : 
- ne rien faire et confier à Grafana par exemple le soin de gérer la date ….. mais ça ne fonctionne pas ( dans le grafana de Madmartigan, la courbe par jour reste décalée d’un jour et le fait de changer le Time zone par défaut ne change rien )
- dans l’absolu l’heure n’a pas d’importance car seule la date compte . La solution serait d’ajouter au couple « energie, date CET » un nombre d’heures permettant d’échapper au changement de jour CET/UTC. Techniquement ce serait a 23h59 mais centrer cette valeur me semble suffisant . Donc ajouter à la valeur ENEDIS 10:30 avant de l’écrire dans la base InfluxDB. Cela peut même être fait précisément en gérant le passage heure été/hivers mais est inutile dans l’absolu .

Pour être puriste, la même moulinette serait a faire pour les champs détails 

**Configuration**
Pas utile 

**Installation type**
Docker

**Version : 0.7.6

**Comment by pbranly** [comment]
Dans le fichier InfluxDB.py la solution est dans les lignes 

        dateObject = datetime.strptime(date, '%Y-%m-%d') - relativedelta(hours=2)

Il doit être possible d’ajouter 11,5 heure(par exemple) . 
Je ne saisis pas le “relativedelta(hours=2 »

**Comment by m4dm4rtig4n** [comment]
Faut que je le vire tt simplement je pense.
Il a rien à faire la ce truc, je sais plus pk j'avais mit ca...
Peut être avant de commencer à jouer avec le TZ

**Comment by pbranly** [comment]
Moi je m'écarterais plus de ce 0h30 d'enedis qui ne veut rien dire

**Comment by m4dm4rtig4n** [comment]
Toi t'est un cas à part ta des TZ de 30mn :D

**Comment by m4dm4rtig4n** [comment]
Ticket en double :
https://github.com/m4dm4rtig4n/enedisgateway2mqtt/issues/67

**Comment by m4dm4rtig4n** [comment]
ticket en double :
https://github.com/m4dm4rtig4n/enedisgateway2mqtt/issues/67

**Comment by m4dm4rtig4n** [comment]
Ticket en double :
https://github.com/m4dm4rtig4n/enedisgateway2mqtt/issues/48

**Comment by pbranly** [comment]
Ce n’est pas en double . L’autre ticket traite du décalage de date MQTT vers Home assistant .
Le problème a été réglé par la variable d’environnement TZ=Europe/Paris peut etre en double avec le codage en dur maintenant.
Ce ticket traite du décalage de date spécifique à InfluxDB 
Philippe

**Comment by pbranly** [comment]
Toi t'est un cas à part ta des TZ de 30mn :D
dans ton cas, le delta T des valeurs fournies par Enedis est de combien et à quelle heure pour ce qui concerne le daily ?
