### ISSUE TITLE
Remontée des consommations horaires

### ISSUE THREAD

**Issue by navycrow** [m4dm4rtig4n/enedisgateway2mqtt#66]
Bonjour,
Sur le site Enedis et également avec le plugin Enedis de Jeedom (que j’utilisais avant de passer sous Home Assistant), il est possible de récupérer sa consommation par tranche de 30 mn ainsi que la puissance max de la journée. C’est très utile pour comprendre quels appareils consomment et de quelle manière.
Je ne vois pas ces infos dans les remontées. Ai-je manqué quelque chose ou cette fonction n’est pas (encore ?) implantée ?

**Comment by m4dm4rtig4n** [comment]
La remonté par tranche de 30min et déjà en place (mode detail).
Pour la puissance je peut l'ajouter sans problème.

**Comment by navycrow** [comment]
Concernant la remontée par tranche de 30 mn, j'ai bien activé `consumption_detail: true` dans le fichier de configuration mais je ne voit pas les valeurs dans les entités créés. Je dois m'y prendre mal.
Pour la puissance max, je trouve que ce serais bien de l'avoir
Et enfin, je me demandais, s'il était possible de faire apparaitre l'index. Je ne sais pas si cette info est dispo dans l'API?

Encore bravo et merci pour ton travail...

**Comment by m4dm4rtig4n** [comment]
La puissance max est déjà push dans le sensor.enedisgateway_TONPDL_subscribed_power et c'est exprimé en kVA = Watt.
Donc pour faire simple si tu est sur une abonnement 8kVA ta puissance max est de 8000W.
