### ISSUE TITLE
Coût HP/HC = 0 avec double plage horaire

### ISSUE THREAD

**Issue by errgonomie** [m4dm4rtig4n/enedisgateway2mqtt#67]
Bonjour,
J'utilise l'addon hassos d'@alexbelgium. 
Mon contrat a double plage horaire qui remonte correctement depuis enedis, mais les résultats sont des coûts nuls. La calcul sans Hc est correct donc j'imagine que la définition des tarifs horaires est ok mais que le code ne gère pas la double plage.
Merci

`numPDL: #xxxx
activationDate: '2019-11-09'
lastUpdate: '2021-11-20T09:22:58Z'
timeLastCall: '2021-11-20T09:22:58Z'
yesterdayDate: '2021-11-19'
yesterday: 41.299
yesterdayLastYearDate: '2020-11-20'
yesterdayLastYear: 34.771
last_week: 248005
daily:
  - '41.29'
  - '36.04'
  - '42.49'
  - '32.93'
  - '35.37'
  - '28.58'
  - '31.26'
current_week: 188.15200000000002
day_1: '41.29'
day_2: '36.04'
day_3: '42.49'
day_4: '32.93'
day_5: '35.37'
day_6: '28.58'
day_7: '31.26'
current_week_last_year: '163.9'
last_month: 1085.333
current_month: '758.7'
current_month_last_year: '545.79'
last_month_last_year: '842.88'
last_year: 13070.585000000012
current_year: '11340.67'
current_year_last_year: '2503.58'
dailyweek:
  - '2021-11-19'
  - '2021-11-18'
  - '2021-11-17'
  - '2021-11-16'
  - '2021-11-15'
  - '2021-11-14'
  - '2021-11-13'
dailyweek_cost:
  - '6.48'
  - '5.64'
  - '6.74'
  - '5.2'
  - '5.59'
  - '4.5'
  - '4.99'
dailyweek_costHP:
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
dailyweek_HP:
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
day_1_HP: 0
day_2_HP: 0
day_3_HP: 0
day_4_HP: 0
day_5_HP: 0
day_6_HP: 0
day_7_HP: 0
dailyweek_costHC:
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
dailyweek_HC:
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
day_1_HC: 0
day_2_HC: 0
day_3_HC: 0
day_4_HC: 0
day_5_HC: 0
day_6_HC: 0
day_7_HC: 0
daily_cost: 6.48
peak_offpeak_percent: 0
monthly_evolution: 28.76
current_week_evolution: 14.79
current_month_evolution: 39
yesterday_evolution: 18.77
friendly_name: enedisgateway_23116353109966
errorLastCall: ''
errorLastCallInterne: ''
current_week_number: 46
offpeak_hours_enedis: HC (2H54-7H54;13H24-16H24)
offpeak_hours:
  - - 2H54
    - 7H54
  - - 13H24
    - 16H24
subscribed_power: 18 kVA
unit_of_measurement: kWh
`

**Comment by errgonomie** [comment]
Installation type
HassIO addons
Version : 0.7.6

**Comment by m4dm4rtig4n** [comment]
Tu peut me partager la partie enedis_gateway du config.yaml (sans les PDL & token bien sur) ?
Merci.

**Comment by schumissimo63** [comment]
Je suis car j'ai le même problème.

**Comment by ioull** [comment]
J'ai aussi le même problème depuis mon passage à la 0.7.6 depuis la 0.7.2
Mon cache a été clearé à priori suite à cette MAJ.

**Comment by errgonomie** [comment]
[config.yaml.txt](https://github.com/m4dm4rtig4n/enedisgateway2mqtt/files/7574440/config.yaml.txt)

**Comment by m4dm4rtig4n** [comment]
Ticket en double :
https://github.com/m4dm4rtig4n/enedisgateway2mqtt/issues/54

**Comment by m4dm4rtig4n** [comment]
Ou pas c'est pas le meme soucis en fait :D

**Comment by YNK-22** [comment]
je suis aussi ayant le même soucis 👍

**Comment by m4dm4rtig4n** [comment]
Bon sur la 0.7.7-dev, je pense avoir fix le soucis

**Comment by YNK-22** [comment]
j'attends la maj et je te confirme ça 👍

**Comment by m4dm4rtig4n** [comment]
Si tu est sur hassio tu n'auras pas la maj normalement.

**Comment by YNK-22** [comment]
oui je suis sur hassos

**Comment by errgonomie** [comment]
Même situation en 0.7.7dev. on est d'accord qu'il suffit de mettre à jour l'addon ? J'ai pas supprimé les db.
Je renvoie logs,conf et état du sensor dès que possible.

**Comment by alexbelgium** [comment]
en fait l'addon était en latest, indépendamment du n°. Je l'ai repassé en réel à partir de la v0.7.7-dev-2 à l'instant ; ce qui signifie maintenant qu'il considère également les versions dev et pas uniquement les latest

**Comment by YNK-22** [comment]
Ça fonctionne pour moi, je récupère les informations HP/HC depuis la maj d'aujourd'hui 👍
