### ISSUE TITLE
Option pour ne pas récupérer tout l'historique

### ISSUE THREAD

**Issue by ioull** [m4dm4rtig4n/enedisgateway2mqtt#68]
Afin de ne pas dépasser la limite des 50 requêtes lorsque l'on fait les tests. Ce serait peut-etre bien d'ajouter une option pour ne pas récupérer l'historique ? 
ou configurer le nombre de requete max faites par cycle ? 

Désolé je ne trouve pas comment mettre le label enhancement sur cette issue :-(

**Comment by m4dm4rtig4n** [comment]
Normalement je bride à 15 query par jour mais je constate que ca ne fonctionne pas chez tt le monde, faudrait que je revois peut être pk.

**Comment by ioull** [comment]
oui mais 15 requêtes ça fait seulement 4 essais ;-)

**Comment by navycrow** [comment]
Sur le site Enedis, depuis l'espace client, il est possible de récupérer un fichier CSV de tout l'historique sur une plage de date en une seule fois.
Ce serait peut-être une solution de pouvoir faire l'initialisation avec ce type de fichier puis les requêtes classiques par la suite ???...

**Comment by YNK-22** [comment]
oui ça serait pas mal de pouvoir le récupérer en une seule fois

**Comment by aladin2000** [comment]
j'aime bien cette idée, ceci pourrait servir ç changer les datas historisées de plus de 3 ans et qui sont en local en csv et injectable dans la base. 
Une idée pour coupler ce module pour enrichir son historique  linky?

**Comment by aladin2000** [comment]
> j'aime bien cette idée, ceci pourrait servir à charger les datas historisées de plus de 3 ans et qui sont en local en csv et injectable dans la base. Une idée pour coupler ce module pour enrichir son historique linky?
Merci pour tout le travail conséquent déjà réalisé.... mais  y a t il un espoir de pouvoir disposer un jour de cette fonction ?  ou faut il considérer ceci au "calandes greques " ?

**Comment by m4dm4rtig4n** [comment]
Non, c'est dans ma todo, faut juste que je trouve du temps pour le faire :D

**Comment by m4dm4rtig4n** [comment]
Hello,

Je suis en train de rework complétement le projet, et la version actuelle deviendra complétement obsoléte.
Je ne traite donc plus de ticket sur cette version.

Merci de patientez encore un petit peu elle ne devrait pas tarder à sortir :)
