### ISSUE TITLE
[BUG] - L'appli crashe apres un certains temps depuis la MAJ 0.7.8-dev

### ISSUE THREAD

**Issue by schumissimo63** [m4dm4rtig4n/enedisgateway2mqtt#76]
MERCI DE RESPECTER LES DIFFERENTS CHAMPS SINON JE CLOS L'ISSUE.

**Description du bug**
L'appli crashe apres un certains avec ce message d'erreur:

Traceback (most recent call last):
  File "/app/main.py", line 654, in <module>
    run(pdl, pdl_config)
  File "/app/main.py", line 243, in run
    f.logLine()
AttributeError: '_io.TextIOWrapper' object has no attribute 'logLine'
[12:48:57] FATAL: The app has crashed. Are you sure you entered the correct config options?

**Type d'installation**
HassIO ?

**Version : 0.7.8-dev

**Comment by m4dm4rtig4n** [comment]
Ce weekend la passerelle à était surcharger pendant un certain temps ce qui as généré par mal de timeout mal gérée de mon coté.
Je vais voir pour mieux les gérer.

**Comment by m4dm4rtig4n** [comment]
J'ai catch les timeout dans la 0.7.8 pour éviter les crash.
