### ISSUE TITLE
[BUG] - PDL must be 14 characters

### ISSUE THREAD

**Issue by pyzimmer** [m4dm4rtig4n/enedisgateway2mqtt#79]
**Description du bug**
Bonjour, j'ai cette erreur dans les log et le numéro de PDL des log n'est pas le même que celui de ma config, bizarre  : 
2021-11-27 12:40:08.427934 - ERROR : Some mandatory parameters are missing :
2021-11-27 12:40:08.428102 - ERROR : - PDL must be 14 characters (390882291869 => 12)

**Configuration**
enedis_gateway:
  05540231470235:
    token: ******
    addresses: true

**Type d'installation** et **Version : X.X.X**
scripts/00-aaa_dockerfile_backup.sh: executing
scripts/00-banner.sh: executing
-----------------------------------------------------------
 Add-on: Enedisgateway2mqtt
 use Enedis Gateway API to send data in your MQTT Broker (latest channel)
-----------------------------------------------------------
 Add-on version: 0.7.7
 You are running the latest version of this add-on.
 System: Home Assistant OS 6.6  (armv7 / raspberrypi3)
 Home Assistant Core: 2021.11.1
 Home Assistant Supervisor: 2021.10.8
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums
 https://github.com/alexbelgium/hassio-addons
scripts/00-global_var.sh: executing
-----------------------------------------------------------
Timezone set from Etc/UTC to Europe/Paris
scripts/99-run.sh: executing
[12:40:05] INFO: Using config file found in /config/enedisgateway2mqtt/config.yaml
Config file is a valid yaml
 
[12:40:05] INFO: Starting the app
 
2021-11-27 12:40:08.427934 - ERROR : Some mandatory parameters are missing :
2021-11-27 12:40:08.428102 - ERROR : - PDL must be 14 characters (390882291869 => 12)
2021-11-27 12:40:08.428236 - ERROR : 
2021-11-27 12:40:08.428346 - ERROR : You can get list of parameters here :
2021-11-27 12:40:08.428463 - ERROR :  => https://github.com/m4dm4rtig4n/enedisgateway2mqtt#configuration-file
2021-11-27 12:40:08.428627 - CRITICAL : -- Stop application --

**Comment by pbranly** [comment]
Ne pas mettre les pdl en clair svp

**Comment by pyzimmer** [comment]
> Ne pas mettre les pdl en clair svp

le pb concerne justement l'incohérence de valeur de PDL. Si je l'enlève comment identifier/reproduire le bug? Quel risque à communiquer un PDL ? On en trouve sur tous les compteurs en bord de route...

**Comment by m4dm4rtig4n** [comment]
Tu as plusieurs PDL ?

**Comment by pyzimmer** [comment]
dans mon fichier un seul, dans la vraie vie 2, voici mon fichie complet :

```
cycle: 3600
debug: false
enedis_gateway:
  05540231470235:
    token: ***
    addresses: true
    plan: BASE
    consumption: true
    consumption_detail: true
    consumption_price_base: 0
    consumption_price_hc: 0
    consumption_price_hp: 0
    offpeak_hours: null
    production: false
    production_detail: false
    refresh_addresses: false
    refresh_contract: false
home_assistant:
  card_myenedis: false
  discovery: false
  discovery_prefix: homeassistant
mqtt:
  client_id: enedis_gateway
  host: MOSQUITO_SERVER
  username: ''
  password: ''
  port: 1883
  prefix: enedis_gateway
  qos: 0
  retain: true
wipe_cache: false

```

**Comment by m4dm4rtig4n** [comment]
D'pù vient 390882291869  ? oO

**Comment by pyzimmer** [comment]
> D'où vient 390882291869 ? oO

Bonne question, si je mets en PDL = 123456789:  j'ai ERROR : - PDL must be 14 characters (123456789=> 9)
mais avec pdl = 05540231470235:  j'ai ERROR : - PDL must be 14 characters (390882291869 => 12)
bizarr

**Comment by pyzimmer** [comment]
avec 01540231470235: j'ai ERROR : - PDL must be 14 characters (116004384925 => 12)
avec 5540231470235: j'ai ERROR : - PDL must be 14 characters (5540231470235 => 13)
on dirait bien un pb de dépassement de capacité de variable...

**Comment by pyzimmer** [comment]
@m4dm4rtig4n avec 95540231470235 ça fonctionne, donc ce n'set pas un dépassement de capacité, mais le 0 en début de chaine qui pose pb

**Comment by pyzimmer** [comment]
j'ai trouvé la parade , avec '05540231470235': ça fonctionne

**Comment by m4dm4rtig4n** [comment]
Ah ok, j'ai pas dû set le format du PDL en String et du coup python le converti en Integer (ce qui explique la perte des 0 devant)

**Comment by m4dm4rtig4n** [comment]
Bon c'est pas ca car de mon coté j'ai justement un PDL qui commande par 0 :p
Mais j'arrive à reproduire ton cas, je regarde et je te tiens au courant

**Comment by m4dm4rtig4n** [comment]
Bon c'est PyYAML qui fait de la merde lors de la conversion, je pense que le plus simple est d'effectivement renseigner le PDL entre quote.
Je MAJ la doc et merci pour la remonté.
