### ISSUE TITLE
[HELP] - DEUX PDL ?

### ISSUE THREAD

**Issue by aladin2000** [m4dm4rtig4n/enedisgateway2mqtt#80]
MERCI DE RESPECTER LES DIFFERENTS CHAMPS SINON JE CLOS L'ISSUE.

**Description de la fonctionnalité**
2 PDL avec le meme token ? est ce possible car je me retrouve avec cette erreur de manière régulière qui me pousse a changer mon token ... 
Ce jour alors que je viens de changer les autorisations et que le constat des deux curl donne un fonctionnement OK avec le script curl pour chacun des deux pdl et le meme token ....

DEBUG :  MQTT Send : enedis_gateway/errorMsg/message => {'usage_point_id': 'PDL2 NO', 'error': 'token_refresh_401', 'description': 'Une erreur est survenue, merci de renouveller vos consentements.', 'user_alert': True}

**Type d'installation**
 HassIO ?

**Version : X.X.X**
0.7.7

**Comment by m4dm4rtig4n** [comment]
Oui c'est tt à fait possible.
Après en ce moment j'ai l'impression qu'il y a des soucis coté Enedis sur les consentement & co et pas mal d'utilisateur ce retrouver avec des PDL bloqué qui les oblige à renouveler leur consentements :/
