### ISSUE TITLE
[HELP] - Grafana et 2 PDL 

### ISSUE THREAD

**Issue by aladin2000** [m4dm4rtig4n/enedisgateway2mqtt#81]
MERCI DE RESPECTER LES DIFFERENTS CHAMPS SINON JE CLOS L'ISSUE.

**Description de la fonctionnalité**
Comment avoir deux PDL au sein de l'interface grafana . 
Faut il un dashboard ou deux ?
**Type d'installation**
 HassIO 
**Version : 0.7.7**

**Comment by pbranly** [comment]
2 grafana sinon ça ferait beaucoup trop gros à lire

**Comment by m4dm4rtig4n** [comment]
En haut à gauche tu as le numéro de PDL, et si tu veut changer les valeurs renseigné par défaut en variable c'est dans la configuration de la dashboard.

![image](https://user-images.githubusercontent.com/7872518/143790847-409c45f2-a2dc-4039-9e40-9854b2b5b860.png)
