### ISSUE TITLE
[HELP] - token_refresh_401

### ISSUE THREAD

**Issue by orionevo14** [m4dm4rtig4n/enedisgateway2mqtt#83]
**Description de la fonctionnalité**
Commande curl semble fonctionner (j'ai bien un retour d'info) mais j'ai l'erreur suivante dans mosquitto :
'error': 'token_refresh_401', 'description': 'Une erreur est survenue, merci de renouveller vos consentements.'

J'ai tenté de renouveler le token à 2 reprises, même résultat. J'ai procédé avec Firefox pour éviter les problèmes avec Chrome.
Fichier de conf d'origine à part le pdl, le token et les tarifs. Les logs indiquent que le fichier est ok :
[18:51:45] INFO: Using config file found in /config/enedisgateway2mqtt/config.yaml
Config file is a valid yaml

**Type d'installation**
HassIO

**Version : X.X.X**
0.7.7

**Comment by gdumonteil** [comment]
J'ai le même problème sur mon installation.

**Comment by cvalentin-dkt** [comment]
Enedis rencontre quelques soucis sur les consentements en ce moment.
Je ne peut malheureusement rien y faire.
Il faut prendre son mal en patiente et renouveler ses consentements entre chaque test.

**Comment by orionevo14** [comment]
Ok, j'avais un doute sur l'origine du pb vu que la requête curl semble fonctionner. merci pour l'info

**Comment by B4dC4rd** [comment]
Idem pour moi. 
Chaque renouvellement me fourni un nouveau token, mais j'ai toujours le message d'erreur.
Apres 8 renouvellement sans succès, j'ai abandonné.

**Comment by orionevo14** [comment]
Pareil ici, je retenterai dans quelques.... semaines

**Comment by errgonomie** [comment]
Pour ma part j'ai activé le redémarrage automatique en cas de crash, ça repart pas forcément du premier coup, mais ça remarche sans changement de token.

**Comment by B4dC4rd** [comment]
Site Enedis en maintenance  👍

**Comment by B4dC4rd** [comment]
Toujours pas de progrès après la maintenance côté Enedis. Le log me renvoie la même erreur toutes les heures. Si le renouvellement ne fonctionne plus, je me demandes si les fournisseurs sont également impacté pour la facturation? Je serais curieux de voir combien d’entre nous sommes affectés en tout cas. Pour l’instant, je ne sais plus quoi faire.

**Comment by orionevo14** [comment]
Je pense qu'il ne faut pas que tu t'inquiètes pour ta facturation 🤣 
Du coup puisque cette méthode ne fonctionne pas, je vais me fabriquer un module téléinfo.

**Comment by m4dm4rtig4n** [comment]
Est-ce que l'un de vous peut m'envoyer sa configuration en privé afin que d'avoir un cas concret ?
Je suis joignable en privé sur Discord si besoin : 
https://discord.gg/DfVJZme

**Comment by Markourai** [comment]
J'ai le même souci, cela fait plusieurs fois que je renouvelle le consentement et change le token mais erreur 401

**Comment by m4dm4rtig4n** [comment]
La 1ere step est de valider que les consentements sont bon, pour ce faire il faut utiliser la commande curl en fin de consentement.
Si celle-ci remonte bien l'information, c'est que le soucis ne viens pas des consentement.
Le message d'erreur en retour n'est pas correcte, faudrait que je debug l'un de vos demande pouvoir pk les API vous remonte ceci.
Essayer de faire step by step :

1. Arrêter le conteneur/service
2. Passer en derniere version stable si ce n'est pas le cas (0.7.7)
2. Supprimer le cache (enedisgateway.db)
3. Revérifier le config.yml au niveau du bloc enedis_gateway en vérifiant qu'il y a bien les quotes (")
```
enedis_gateway:
  "XXXXXXXXXXXXXX":
    token: "YOUR_TOKEN"   
```
4. Relancer le conteneur/service.

**Comment by orionevo14** [comment]
Aucun changement chez moi, la requête curl fonctionne toujours mais pas l'add-on et j'ai tjs le même message d'erreur

**Comment by Donokami** [comment]
Pareil de mon côté, aucun changement après suppression du cache et la mise en double quote, malgré une commande curl somme toute fonctionnelle.

**Comment by m4dm4rtig4n** [comment]
> Pareil de mon côté, aucun changement après suppression du cache et la mise en double quote, malgré une commande curl somme toute fonctionnelle. **EDIT: J'ai refait la manip une deuxième fois, en redémarrant également Home Assistant, et cette fois-ci ça a marché !**

Pour ca que je suis pas fan d'hassio, ta souvent des fonctionnement aléatoire incompréhensible...



> Aucun changement chez moi, la requête curl fonctionne toujours mais pas l'add-on et j'ai tjs le même message d'erreur

Réessaie une 2eme fois comme @Donokami j'ai envie de dire :d

**Comment by JigSawFr** [comment]
De mon côté, avoir ajouté les quotes au numéro de PDL a résolu le problème ! Merci @m4dm4rtig4n !

**Comment by orionevo14** [comment]
> > Aucun changement chez moi, la requête curl fonctionne toujours mais pas l'add-on et j'ai tjs le même message d'erreur
> 
> Réessaie une 2eme fois comme @Donokami j'ai envie de dire :d

ah bin ouais effectivement, après redémarrage ça marche :)

**Comment by m4dm4rtig4n** [comment]
Cool je clos le ticket :)
