### ISSUE TITLE
64 bits option in raspi3b

### ISSUE THREAD

**Issue by aladin2000** [m4dm4rtig4n/enedisgateway2mqtt#89]
Bonjour 
Je suis sur les dernières version ha et je suis passé sur un noyau 64bits et alors que l'addon 0.7.7 ne le posait pas de pb, ce matin j'ai cette erreur au démarrage 

**Image db21ed7f/aarch64-addon-enedisgateway2mqtt:0.7.7 does not exist for addon_db21ed7f_enedisgateway2mqtt**

J'ai tenté de réinstaller sans succes

Une idée ?

**Comment by alexbelgium** [comment]
Si un restore a été fait depuis un HA en 32 bits vers un en 64bits ça va causer beaucoup de problèmes... As tu essayé de desinstaller et réinstaller ?

**Comment by aladin2000** [comment]
et désinstaller/résinstaller  , cela a réglé le pb   ( et surement un reconfigure de souvenir)
