### ISSUE TITLE
report des infos de +sieurs PDL dans la BDD

### ISSUE THREAD

**Issue by alainvdu69** [m4dm4rtig4n/enedisgateway2mqtt#94]
Bonjour,

Je suis passé à la v7.7 depuis 2 jours (avec raz de bdd) et en jetant un oeil sur son contenu, je suis perplexe.
J'ai 2 PDL.
La table contrat contient les 2 PDL, mais dit sur l'un "token refresh" alors que le test curl réalisé à l'instant fonctionne.
Les tables addresses, config et consommation ne contiennent qu'un seul PDL  (celui qui n'est pas en token_refresh).

Dans la table de conso détail, tout est en measure type BASE (c'est bien le cas de mon contrat actuel, même si j'étais HC/HP il y a qques mois) alors que, pour autant, dans la table contrat, il y a bien la présence de la période HC : il serait donc logique d'utiliser cette valeur pour classer les conso entre HC/HP ?

Dans l'ancienne BDD (issue de plusieurs versions < 7.7), il y a bien des infos sur les 2 PDL dans toutes les tables.

Cordialement.

**Comment by alainvdu69** [comment]
J'ai du mieux en ayant supprimé la ligne du PDL en "token refresh" dans la table contrat.

Je ne sais pas à quand cela remonte, mais vu que le message "token refresh" est bigrement aléatoire et ne signifie pas nécessairement que c'est le cas, je pense qu'il faudrait trouver le moyen de remonter l'info dans un compteur qui s'incrémente et le repasser à 0 dès que c'est bon.

Ensuite, c'est à l'utilisateur de suivre la progression du compteur et de vraiment se soucier de la chose si ça ne revient pas à 0.

**Comment by m4dm4rtig4n** [comment]
```Dans la table de conso détail, tout est en measure type BASE (c'est bien le cas de mon contrat actuel, même si j'étais HC/HP il y a qques mois) alors que, pour autant, dans la table contrat, il y a bien la présence de la période HC : il serait donc logique d'utiliser cette valeur pour classer les conso entre HC/HP ?```

La présence de la période HC dans la table est simplement une remonté d'information disponible via les API d'Enedis.
Libre à moi (ou toi) de l'utiliser.
Tu as peut être défini le `offpeak_hours` qui fait que tu surcharge cette valeur remonté par les API.

Il me faudrait ton config.yml pour valider.

```
Je ne sais pas à quand cela remonte, mais vu que le message "token refresh" est bigrement aléatoire et ne signifie pas nécessairement que c'est le cas, je pense qu'il faudrait trouver le moyen de remonter l'info dans un compteur qui s'incrémente et le repasser à 0 dès que c'est bon.
```

L'erreur  "token refresh" est remonté bien souvent comme étant mauvais code d'erreur. (faudrait que je prennent le temps d'analyser coté API).
Le tout est de valider avec le curl que les consentements sont bon.

**Comment by alainvdu69** [comment]
Merci pour les réponses.
    offpeak_hours: ""
Il est préférable que je le dégage carrément ?

Sinon, pour le 401, je suis en cours de test d'un sensor de ce type :
`# pour savoir si consentement ENEDIS valable
  - platform: rest
    resource: https://enedisgateway.tech/api
    name: "consentement_19177xxxxxxx"
    method: POST
    headers:
      Authorization: 'I8ptzGAxxxxxxxxxxxxxx'
      Content-Type: application/json
    payload: '{"type": "consumption_load_curve","usage_point_id": "19177xxxx","start": "2021-11-26","end": "2021-11-27"}'
    json_attributes:
      - usage_point_id
      - error
      - description
      - user_alert
    value_template: '{% if "401" in "{value_json.error}" %} KO {% else %} OK {% endif %}'
    scan_interval: 21600`

Je baisserais bien le scan interval, mais je pense que cela va bouffer dans les requêtes permises ...

**Comment by alainvdu69** [comment]
bonjour,
je viens de tester en virant la présence du offpeak ... sanction immédiate ...

Traceback (most recent call last):
  File "/app/main.py", line 656, in <module>
    run(pdl, pdl_config)
  File "/app/main.py", line 328, in run
    ha_discovery_consumption = detail.getDetail(headers, cur, con, client, pdl, pdl_config, "consumption",
  File "/app/detail.py", line 154, in getDetail
    best_plan_percent = f"{abs(round(result[year][month]['base_vs_offpeak'], 2))}"
KeyError: 'base_vs_offpeak'
[14:22:34] FATAL: The app has crashed. Are you sure you entered the correct config options?

**Comment by alainvdu69** [comment]
j'ai essayé en mettant 22H00-6H00  ou 22h00-6h00 : même sanction
il n'y a que "" qui est valable.

**Comment by alainvdu69** [comment]
j'ai une autre question : la colonne "fail" dans les tables consumption : la valeur 1 indiquerait un souci de récup ... mais est-ce qu'il y a d'autres tentatives ?
sinon, il faut vérifier de temps en temps, virer les lignes et laisse faire ?

**Comment by m4dm4rtig4n** [comment]
En fait ca compte le nombre de fail et bout d'un certain nombre de fail, la date est "ban" pour eviter de spam les API pour des informations qui ne sont pas disponible chez Enedis.
