### ISSUE TITLE
[BUG] - InfluxDB en SSL non supporté

### ISSUE THREAD

**Issue by Jeoffreybauvin** [m4dm4rtig4n/enedisgateway2mqtt#96]
https://github.com/m4dm4rtig4n/enedisgateway2mqtt/blob/master/app/main.py#L622

Il faudrait le mettre en config :)

**Description du bug**
Le scheme est forcé en http pour se connecter à influxdb. 

**Configuration**

**Type d'installation**
Docker

**Version : 0.7.7**

**Comment by cvalentin-dkt** [comment]
Ca arrivera avec la 0.7.8.
