### ISSUE TITLE
[BUG] - myenedis: in the calculations various precisions needed (solutions proposed below)

### ISSUE THREAD

**Issue by vingerha** [m4dm4rtig4n/enedisgateway2mqtt#97]
**Description du bug**
In the output used for the linky card, 
- the date of yesterday (yesterdayLastYearDate) is wrong, leading to incorrect % calculations
- the last-month and last-month-last-year are not properly calculated as they donot start with day 1 of the month and take in more values than for that month

I altered myenedis.py which is now working OK for me. for testing I used the data from the SQLite db and (!) compared to the saninho integration/card.
You can verify if you are happy with my changes

Version in use: latest
[myenedis.txt](https://github.com/m4dm4rtig4n/enedisgateway2mqtt/files/7823291/myenedis.txt)

**Comment by m4dm4rtig4n** [comment]
Create Pull Request plz.
