### ISSUE TITLE
Ratios incohérents - carte linky 

### ISSUE THREAD

**Issue by floow77** [m4dm4rtig4n/enedisgateway2mqtt#98]
Hello,

Les ratios affichés dans la carte ne semblent pas correspondre aux données récupérées.
![DA759215-FEA9-4D0B-9D14-603EA72884A7](https://user-images.githubusercontent.com/72973078/148671950-aa0cfbab-0f35-49b5-97e5-4af553fba2c2.jpeg)

un bug ou un problème de paramétrage de mon côté ?

**Comment by m4dm4rtig4n** [comment]
Si ca ne te dérange pas, peut tu m'envoyer ta configuration (config.yaml) par mail stp ?
m4dm4rtig4n@gmail.com

**Comment by floow77** [comment]
En complément, la consommation de la veille (HP/HC) affichée en haut à gauche est fausse (d'apres les données enedis). Celle affichée dans le détail de la semaine semble être la bonne.

**Comment by m4dm4rtig4n** [comment]
Quand tu dit fausse, c'est à dire ?
SI ca diffère de quelques kw il est possible que ce soit juste une différence de timezone.
Tu as set quelle timezone ?

**Comment by floow77** [comment]
Effectivement la différence de conso est très minime, j'ai l'impression que c'est une histoire d'arrondi.
