### ISSUE TITLE
[HELP] - 

### ISSUE THREAD

**Issue by taKi78540** [m4dm4rtig4n/enedisgateway2mqtt#99]
**Description de la fonctionnalité**

Je ne parviens pas à obtenir les données dans grafana.

J’ai mis en place influxDB ainsi que grafana mais les données ne remontent pas dans grafana.

Ce que j’ai fais :

Mise en place de enedisgateway2mqtt via MQTT : OK
Les données apparaissent correctement dans la carte lovelace : OK
Installation InfluxDB v1.8 via HA + création DB « homeassistant »
Création user homeassistant & grafana & enedis (admin).
Modification configuration.yaml
Les données homeassistant sont disponible dans InfluxDB
Installation de Grafana + ajout de la source influxDB « homeassistant »
Modification du config.yaml « enedisgateway2mqtt » avec les lignes suivantes :
influxdb:
host: 10.0.0.122
port: 8086
token: « enedis:password »
org: « - »
bucket: « homeassistant/autogen »

Ajout du template .json grafana.
Modification du PDL dans les parametres du dashboard.
J’en suis là et les tableaux sont vides.
Avez-vous une idée où se situe mon erreur ?

**Type d'installation**
HassIO

Version : Home Assistant OS 7.1

**Comment by pbranly** [comment]
Bonjour,
Le nom du lien que tu donnes dans Grafana pour lier ta base enedisgateway doit être Linky. 
Sinon tu dois changer ce nom partout dans le json.

Cdlt
Philippe
